on:
  push:
    branches:
      - main
name: 🚀 Deploy API on push
jobs:
  api-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: � Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
            **/.env*

      - name: 🎬 Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_MAC }}

      - name: 🔍 Add SSH Key to Known Hosts
        run: |
          ssh-keyscan -t rsa -p 2222 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: 🏃 Run Database Migrations
        run: |
          ssh -p 2222 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd ~/api.gpsdodev.com.br && \
          /opt/cpanel/ea-php83/root/usr/bin/php /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader && \
          /opt/cpanel/ea-php83/root/usr/bin/php artisan migrate --force && \
          /opt/cpanel/ea-php83/root/usr/bin/php artisan cache:clear && \
          /opt/cpanel/ea-php83/root/usr/bin/php artisan route:clear && \
          /opt/cpanel/ea-php83/root/usr/bin/php artisan config:clear && \
          /opt/cpanel/ea-php83/root/usr/bin/php artisan view:clear"
